# 05 Exercise - Making and Modifying Matrices

In this exercise set, we are going are going to work with a dataset about the weather in Berlin. This will give us plenty of practice with 2D arrays.

In [1]:
# DON'T MODIFY THIS CELL, ONLY RUN IT.

# Importing numpy as np.
import numpy as np

# List of weather in Berlin in Celsius taken from Wikipedia
row_description = ["Record High", "Daily Mean", "Record Low"]
berlin_weather_list = [
    [15.1, 18.0, 25.8, 30.8, 32.7, 35.4, 37.3, 38.0, 32.3, 27.7, 20.4, 15.6],
    [0.1, 0.9, 43, 9.0, 14.0, 16.8, 19.1, 18.5, 14.2, 9.4, 4.4, 1.0],
    [-25.3, -22.0, -16.0, -7.4, -2.8, 1.3, 4.9, 4.6, -0.9, -7.7, -12.0, -24.0]
]

# Print out the data
for idx, row in enumerate(row_description):
    print(f'{row}:\n{berlin_weather_list[idx]}\n')

Record High:
[15.1, 18.0, 25.8, 30.8, 32.7, 35.4, 37.3, 38.0, 32.3, 27.7, 20.4, 15.6]

Daily Mean:
[0.1, 0.9, 43, 9.0, 14.0, 16.8, 19.1, 18.5, 14.2, 9.4, 4.4, 1.0]

Record Low:
[-25.3, -22.0, -16.0, -7.4, -2.8, 1.3, 4.9, 4.6, -0.9, -7.7, -12.0, -24.0]



## Exercise 1: Make a 2D Array

Make a 2D array called <b>berlin_weather</b> from the <b>berlin_weather_list</b> and check the size of the array.

In [2]:
# Convert the berlin_weather_list into a NumPy array
berlin_weather_list = np.array(berlin_weather_list)

# Find the shape of the array
berlin_weather_list.shape

(3, 12)

## Exercise 2: Changing Enteries

There is a typo in the dataset. The average temperature for March daily average should be 4.3 not 43. Fix the mistake by using indexing, not by modifying the original list.

In [6]:
# Setting the daily average for March to be 4.3
print(f'Before: {berlin_weather_list[1, 2]}')

berlin_weather_list[1, 2] /= 10

print(f'After: {berlin_weather_list[1, 2]}')

Before: 43.0
After: 4.3


## Exercise 3:  Printing Out the Data

Print out the column containing the data for June.

In [12]:
# Data for June
for desc, data in zip(row_description, berlin_weather_list[:, 5]):
  print(f'{desc} for june: {data}')

Record High for june: 35.4
Daily Mean for june: 16.8
Record Low for june: 1.3


## Exercise 4: Reshaping the Data

### Exercise 4a:
Take the row containing the record low temperatures and reshape it into a matrix with 6 rows and 2 columns.

In [16]:
# Reshape the record low temperatures
record_low_temperatures = berlin_weather_list[2, :]\
                            .reshape(6, 2)\
                            .copy()

record_low_temperatures

array([[-25.3, -22. ],
       [-16. ,  -7.4],
       [ -2.8,   1.3],
       [  4.9,   4.6],
       [ -0.9,  -7.7],
       [-12. , -24. ]])

### Exercise 4b:
Take average of pairs of consecutive months of the record low temeratures.

<i>Hint: </i> Use what you found in Exercise 4a and the mean method.

In [17]:
# Take average of pairs of consecutive months.
record_low_temperatures.mean(axis=1)

array([-23.65, -11.7 ,  -0.75,   4.75,  -4.3 , -18.  ])

## Exercise 5: Max and Min
Find the maximum and minimum values over all the rows.

In [18]:
# The max over all the rows
berlin_weather_list.max(axis=1)

array([38. , 19.1,  4.9])

In [19]:
# The min over all the rows
berlin_weather_list.min(axis=1)

array([ 15.1,   0.1, -25.3])

## Exercise 6: Boolean Matrices

### Exercise 6a:
For how many rows are the average temperature over 10 degrees Celsius?

In [21]:
# The total number of months with average over 10 degrees Celsius
(berlin_weather_list > 10).sum(axis=1)

array([12,  5,  0])

### Exercise 6b:
Are there months where the record high is subzero?

In [22]:
# Any record highs below zero?
(berlin_weather_list < 0).any()

True

What about months where the daily average is subzero?

In [23]:
# Any averages below zero?
(berlin_weather_list.mean(axis=1) < 0).any()

True

## Moral of the Story

In this exercise set, we have seen that reshaping and other techniques are vital for handeling data. Being comfortable with matricies in NumPy is a valuable skill.