# 07 Exercise - Basic Linear Algebra

This exercise set is all about doing standard linear algebra exercises using NumPy.

In [1]:
#DON'T MODIFY THIS CELL, ONLY RUN IT.

# Importing NumPy as np.
import numpy as np

## Exercise 1: Import the Linalg Submodule

In [2]:
# Importing the linalg submodule from NumPy
from numpy import linalg as la

## Exercise 2: Simple Vector Operations

### Exercise 2a:
Are any of the vectors $[1, 2, 3]$  and $[2, 3, 4]$  parallel? What about orthogonal?

In [3]:
# Make the vectors
vec_1 = np.array([1, 2, 3])
vec_2 = np.array([2, 3, 4])

# Checking if parallel

# Checking if orthogonal
print('Orthogonal:', np.dot(vec_1, vec_2) == 0)

Angle 0.12186756768575456
Orthogonal: False


### Exercise 2b:
Can you find the angle between the vector $[1, 2, 3]$ and $[2, 3, 4]$?

In [4]:
# Defining the angle function
def angle(vec_1, vec_2):
  return np.arccos(np.dot(vec_1, vec_2) / (la.norm(vec_1) * la.norm(vec_2)))

# Finding the angle
print('Angle', angle(vec_1, vec_2))

Angle 0.12186756768575456


## Exercise 3: Simple Matrix Operations

Define the matrices
$$ A=
\begin{bmatrix}
1&1&2\\
1&1&1\\
1&1&1
\end{bmatrix}\quad \text{and}\quad B=
\begin{bmatrix}
1&0&0\\
0&1&-2\\
0&0&1
\end{bmatrix}.
$$

### Exercise 3a:
Find the matrix product $AB$.

In [6]:
# Defining the matrices
A = np.array([[1, 1, 2],
              [1, 1, 1],
              [1, 1, 1]])

B = np.array([[1, 0, 0],
              [0, 1, -2],
              [0, 0, 1]])

# Finding the matrix product AB
A @ B

array([[ 1,  1,  0],
       [ 1,  1, -1],
       [ 1,  1, -1]])

### Exercise 3b:
Find the matrix product $B^{-1}A^5$.

In [7]:
# Find the matrix power
np.matmul(
    la.matrix_power(B, -1),
    la.matrix_power(A, 5)
)

array([[142., 142., 185.],
       [327., 327., 426.],
       [109., 109., 142.]])

### Exercise 3c:
Find the transpose of $A$, namely $A^T$. Compute the product $A A^T$.

In [8]:
# Finding the transpose of $A$
A_transpose = A.transpose()

# Finding the product of $AA^T$
A @ A_transpose

array([[6, 4, 4],
       [4, 3, 3],
       [4, 3, 3]])

## Exercise 4: Balancing Chemical Equations

In this exercise we are going to use NumPy to balance a set of chemical equations. The question is how to balance the equation
$$x*C_4H_{10}+y*O_2 = v*H_2O + w*CO_2.$$
Written as vectors this becomes
$$x*[4,10,0]+y*[0,0,2]=z*[0,2,1] + w*[1,0,2],$$
or equivalently,
$$
\begin{bmatrix}
4&0&0\\
10&0&-2\\
0&2&-1
\end{bmatrix}
\begin{bmatrix}
x\\ y\\ z
\end{bmatrix}
=w*\begin{bmatrix}
1\\ 0\\ 2
\end{bmatrix}.
$$

### Exercise 4a:
Find out if the matrix is invertible.

In [11]:
# Checking if the matrix is invertible
chem_matrix = np.array([[4, 0, 0],
                        [10, 0, -2],
                        [0, 2, -1]])

np.allclose(
    np.dot(la.inv(chem_matrix), chem_matrix),
    np.eye(3)
)

True

### Exercise 4b:
Solve the linear system with $w=1$.

In [ ]:
# Finding a solution


### Exercise 4c:
Having 0.25 of a carbon atom doesn’t really make sense. Multiply the vector with the whole numbers from 1 to 10 to see when the solution consists of only whole numbers.

In [ ]:
# Print out the multiples from 1 to 10


### Exercise 4d:
Write up the balanced equation, in other words, what is $x,$ $y,$ $z,$ and $w$?

## Moral of the Story

NumPy's linear algebra module makes working with linear algebra easy. In many universities around the world, NumPy is used in courses for linear algebra. In Exercise 4 above, you saw that one can use NumPy to balance chemical equations. Many other applications of linear algebra exist and you can check out the article: https://medium.com/@jeremyjkun/here-s-just-a-fraction-of-what-you-can-do-with-linear-algebra-633383d4153f for more examples!