In [ ]:
import numpy as np

In [ ]:
first_vector = np.array([1, 2, 4])
second_vector = np.array([2, -1, 9])

In [ ]:
first_matrix = np.array([[1, 2, 9],
                         [3, 10, -2],
                         [-3, 5, 3]])

second_matrix = np.array([[1, 2, 9],
                          [0, 0, -2],
                          [-3, 8, 3]])

### Vector addition

In [ ]:
first_vector + second_vector

array([ 3,  1, 13])

### Vector subtraction

In [ ]:
first_vector - second_vector

array([-1,  3, -5])

### Matrix addition

In [ ]:
first_matrix + second_matrix

array([[ 2,  4, 18],
       [ 3, 10, -4],
       [-6, 13,  6]])

### Matrix subtraction

In [ ]:
first_matrix - second_matrix

array([[ 0,  0,  0],
       [ 3, 10,  0],
       [ 0, -3,  0]])

### Scalar multiplication vector

In [ ]:
2 * first_vector

array([2, 4, 8])

### Scalar multiplication matrix

In [ ]:
2 * first_matrix

array([[ 2,  4, 18],
       [ 6, 20, -4],
       [-6, 10,  6]])

### Dot product

In [ ]:
np.dot(first_vector, second_vector)

36

In [ ]:
def are_orthogonal(vec_1, vec_2):
  return np.dot(vec_1, vec_2)

In [ ]:
are_orthogonal(first_vector, second_vector)

36

### Cross product

In [ ]:
np.cross(first_vector, second_vector)

array([22, -1, -5])

In [ ]:
np.cross(np.arange(2), np.arange(1, 3))

array(-1)

In [ ]:
cross = np.cross(first_vector, second_vector)

In [ ]:
np.dot(first_vector, cross)

0

In [ ]:
np.dot(second_vector, cross)

0

##@ More complex algebra

In [ ]:
from numpy import linalg

## Length of vector

In [ ]:
linalg.norm(first_vector)

4.58257569495584

In [ ]:
linalg.norm(second_vector)

9.273618495495704

In [ ]:
linalg.norm(first_matrix)

15.556349186104045

In [ ]:
linalg.norm(second_matrix)

13.114877048604

In [ ]:
def angle(vec_1, vec_2):
  cos_angle = np.dot(vec_1, vec_2) / (linalg.norm(vec_1) * linalg.norm(vec_2))
  return np.arccos(cos_angle)

In [ ]:
angle(first_vector, second_vector)

0.5602591049467772

### Matrix product

In [ ]:
first_matrix @ second_matrix

array([[-26,  74,  32],
       [  9, -10,   1],
       [-12,  18, -28]])

In [ ]:
first_matrix @ first_vector

array([41, 15, 19])

In [ ]:
np.matmul(first_matrix, first_vector)

array([41, 15, 19])

In [ ]:
np.eye(3) @ first_matrix

array([[ 1.,  2.,  9.],
       [ 3., 10., -2.],
       [-3.,  5.,  3.]])

In [ ]:
np.eye(3) @ first_vector

array([1., 2., 4.])

### Matrix power

In [ ]:
first_matrix @ first_matrix @ first_matrix @ first_matrix

array([[ 3109,  6980, -1469],
       [ 2967, 11888,  1316],
       [ 2157,  4213,   939]])

In [ ]:
linalg.matrix_power(first_matrix, 4)

array([[ 3109,  6980, -1469],
       [ 2967, 11888,  1316],
       [ 2157,  4213,   939]])

### Transpose

In [ ]:
first_matrix

array([[ 1,  2,  9],
       [ 3, 10, -2],
       [-3,  5,  3]])

In [ ]:
first_matrix.T

array([[ 1,  3, -3],
       [ 2, 10,  5],
       [ 9, -2,  3]])

In [ ]:
first_matrix.transpose()

array([[ 1,  3, -3],
       [ 2, 10,  5],
       [ 9, -2,  3]])

## Linear systems

In [ ]:
linalg.det(first_matrix)

439.00000000000006

In [ ]:
linalg.det(second_matrix)

28.00000000000001

In [ ]:
non_invertible = np.array([[1, 2, 0],
                            [-2, 10, 3],
                            [-3, 8, 3]])

non_invertible

array([[ 1,  2,  0],
       [-2, 10,  3],
       [-3,  8,  3]])

In [ ]:
linalg.det(non_invertible)

3.108624468950436e-15

In [ ]:
np.around(linalg.det(non_invertible), 10)

0.0

### Inverse matrices

In [ ]:
linalg.inv(first_matrix) @ first_matrix

array([[ 1.00000000e+00,  2.22044605e-16, -2.22044605e-16],
       [-1.38777878e-17,  1.00000000e+00,  1.38777878e-17],
       [ 3.46944695e-18, -1.38777878e-17,  1.00000000e+00]])

In [ ]:
np.round(linalg.inv(first_matrix) @ first_matrix, 10)

array([[ 1.,  0., -0.],
       [-0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [ ]:
linalg.inv(non_invertible)

array([[ 1.93011413e+15, -1.93011413e+15,  1.93011413e+15],
       [-9.65057063e+14,  9.65057063e+14, -9.65057063e+14],
       [ 4.50359963e+15, -4.50359963e+15,  4.50359963e+15]])

### Solving linear systems

#### Unique solution

In [ ]:
linalg.solve(first_matrix, first_vector)

array([-0.58769932,  0.39407745,  0.08883827])

In [ ]:
first_matrix @ linalg.solve(first_matrix, first_vector)

array([1., 2., 4.])

#### No solution

In [ ]:
linalg.solve(non_invertible, first_vector)

array([ 5.79034238e+15, -2.89517119e+15,  1.35107989e+16])

In [ ]:
non_invertible @ linalg.solve(non_invertible, first_vector)

array([-2., 10., 10.])

#### Multiple solutions

In [ ]:
third_vector = np.array([1, -2, -3])

In [ ]:
linalg.solve(non_invertible, third_vector)

array([1., 0., 0.])

In [ ]:
non_invertible @ linalg.solve(non_invertible, third_vector)

array([ 1., -2., -3.])